# Generated by Django 2.2.5 on 2021-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('blog', 'blog'), ('smart_store', 'smart_store'), ('smart_place', 'smart_place')], max_length=15, null=True),
        ),
    ]
