# Generated by Django 2.2.5 on 2021-01-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_type'),
        ('users', '0006_auto_20210116_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_posts',
            field=models.ManyToManyField(related_name='fav_posts', to='posts.Post'),
        ),
    ]
